// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/Banner.tsx";
import * as $$1 from "./islands/Card.tsx";
import * as $$2 from "./islands/Counter.tsx";
import * as $$3 from "./islands/NavBar.tsx";
import * as $$4 from "./islands/PricingCard.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/Banner.tsx": $$0,
    "./islands/Card.tsx": $$1,
    "./islands/Counter.tsx": $$2,
    "./islands/NavBar.tsx": $$3,
    "./islands/PricingCard.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
